# Generated by Django 3.2 on 2022-03-29 19:13

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0002_remove_tag_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='adress',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='post',
            name='body',
            field=ckeditor.fields.RichTextField(default=''),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(default='Post Title', max_length=100),
        ),
    ]
