# Generated by Django 3.2 on 2022-04-11 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0004_rename_adress_post_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='latitude',
            field=models.DecimalField(decimal_places=10, default=0.0, max_digits=30),
        ),
        migrations.AddField(
            model_name='post',
            name='longitude',
            field=models.DecimalField(decimal_places=10, default=0.0, max_digits=30),
        ),
    ]
