# Generated by Django 3.2 on 2022-03-29 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_profile_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(default='pictures/profile_pictures/default.jpg', editable=False, upload_to='pictures/profile_pictures'),
        ),
    ]
