# Generated by Django 3.2 on 2022-03-29 19:13

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_profile_profile_picture'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='date_posted',
            new_name='date_created',
        ),
        migrations.AlterField(
            model_name='profile',
            name='body',
            field=ckeditor.fields.RichTextField(default=''),
        ),
        migrations.AlterField(
            model_name='profile',
            name='description',
            field=models.CharField(default='', max_length=200),
        ),
    ]
